FROM  node:18

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .

CMD ["npm","start"]

FROM mysql:8.0.26

ENV MYSQL_ROOT_PASSWORD=
ENV MYSQL_DATABASE=placas
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=

COPY ./sql-scripts/ /docker-entrypoint-initdb.d/

EXPOSE 3306





